name: Cloudflare Pages Deployed

on:
  check_run:
    types: [completed]

# only run test with latest commit
concurrency:
  group: ${{ github.workflow }}

jobs:
  test:
    name: Deployed
    runs-on: [self-hosted]
    env:
      NODE_OPTIONS: --max-old-space-size=6144
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: github.event.check_run.pull_requests[0]

    steps:
      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: E2E Test
          status: in_progress

      - name: Set testing state
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_includes: 'Playwright tests'
          pr_number: ${{ github.event.check_run.pull_requests[0].number }}
          message: |
            ## Playwright tests
            ### testing...
            [Test job](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Install dependencies
        run: yarn install

      - name: Check github object
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT

      - uses: LouisBrunner/checks-action@v1.1.1
        if: success() || failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: E2E Test
          status: completed
          conclusion: ${{ job.status }}
