name: Cloudflare Pages Deployed

on:
  check_run:
    types: [completed]

jobs:
  test:
    name: Deployed
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=6144
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: E2E Test
          status: in_progress

      - name: Check github object
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT

      - uses: LouisBrunner/checks-action@v1.1.1
        if: success() || failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: E2E Test
          status: completed
          conclusion: ${{ job.status }}
